name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main # 你写代码的主分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save

      - name: Setup git config
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Create .nojekyll to disable Jekyll build
        run: echo "" > public/.nojekyll

      - name: Generate and deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          # 配置远程仓库用token认证，格式是 https://<token>@github.com/用户名/仓库.git
          git remote set-url origin https://x-access-token:${DEPLOY_TOKEN}@github.com/<用户名>/<仓库>.git

          npx hexo clean
          npx hexo generate
          npx hexo deploy --debug
