name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save

      - name: Setup Git identity and credentials
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global credential.helper store
          echo "https://${{ secrets.DEPLOY_TOKEN }}:@github.com" > ~/.git-credentials
      - name: Debug current directory and files
        run: |
          pwd
          ls -la
      - name: Generate and Deploy
        id: deploy
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          npx hexo clean
          npx hexo generate
          cp CNAME public/CNAME
          npx hexo deploy
