name: Hexo CI Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 监听 Hexo 源码仓库的 main 分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npx hexo generate

      - name: Deploy to redhat123456.github.io
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          DEPLOY_REPO: github.com/redhat123456/redhat123456.github.io.git
          DEPLOY_BRANCH: master
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_EMAIL}"
          npx hexo deploy
